parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
    experimentalObjectRestSpread: true

plugins:
  - react

env:
  es6: true

extends:
  - eslint:recommended
  - plugin:react/recommended

globals:
  require: false